global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'eth-exporter'
    static_configs:
      - targets: ['eth-exporter:9333']
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'geth'
    static_configs:
      - targets: ['geth:6060']
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /debug/metrics/prometheus

  - job_name: 'nimbus'
    static_configs:
      - targets: ['nimbus:8001']
    scrape_interval: 15s
    scrape_timeout: 10s
